twitter-dart/twitter-api-v2

- README.md
> docs: Fixed link

- .vscode/settings.json
- CHANGELOG.md
- example/example.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/twitter_client.dart
- pubspec.yaml
> feat: Add for the issue (#6)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: Add for the issue (#7)

- README.md
> docs: Fixed example

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweet_meta.dart
- lib/src/service/tweets/tweet_meta.freezed.dart
- lib/src/service/tweets/tweet_meta.g.dart
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
> feat: Add Tweets:Quote Tweets endpoint (#8)

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweets_service.dart
> feat: Added Search Tweets endpoints (#10)

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweets_service.dart
> feat: Added Tweets Lookup endpoints (#13)

- .vscode/settings.json
- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/client/client.dart
- lib/src/client/client_context.dart
- lib/src/client/oauth1_client.dart
- lib/src/client/oauth2_client.dart
- lib/src/client/oauth_tokens.dart
- lib/src/client/user_context.dart
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/twitter_service.dart
- lib/src/service/users/users_service.dart
- lib/src/twitter_api.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
- test/twitter_api_v2_test.dart
> fix: fixed for the issue (#44)

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweet_count_data.dart
- lib/src/service/tweets/tweet_count_data.freezed.dart
- lib/src/service/tweets/tweet_count_data.g.dart
- lib/src/service/tweets/tweet_count_meta.dart
- lib/src/service/tweets/tweet_count_meta.freezed.dart
- lib/src/service/tweets/tweet_count_meta.g.dart
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
> feat: Added Tweet Counts endpoints (#12)

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
> feat: Added Tweets Bookmarks endpoints (#2)

- CHANGELOG.md
- README.md
- lib/src/service/users/users_service.dart
> feat: Added Users Lookup endpoints (#23)

- CHANGELOG.md
- README.md
- lib/src/service/spaces/space_data.dart
- lib/src/service/spaces/space_data.freezed.dart
- lib/src/service/spaces/space_data.g.dart
- lib/src/service/spaces/space_meta.dart
- lib/src/service/spaces/space_meta.freezed.dart
- lib/src/service/spaces/space_meta.g.dart
- lib/src/service/spaces/space_state.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/twitter_service.dart
- lib/src/twitter_api.dart
- lib/twitter_api_v2.dart
> feat: Added Spaces Search endpoint (#23)

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/twitter_api.dart
- pubspec.yaml
> fix: fixed typo

- CHANGELOG.md
- lib/src/service/base_service.dart
> fix: fix for the issue (#41)

- CHANGELOG.md
- lib/src/twitter_exception.dart
- pubspec.yaml
> fix: fixed for the issue (#48)

- README.md
- example/example.dart
> docs: fixed docs

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweet_count_meta.dart
- lib/src/service/tweets/tweet_count_meta.freezed.dart
- lib/src/service/tweets/tweet_count_meta.g.dart
- lib/src/service/tweets/tweet_meta.dart
- lib/src/service/tweets/tweet_meta.freezed.dart
- lib/src/service/tweets/tweet_meta.g.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/user_meta.dart
- lib/src/service/users/user_meta.freezed.dart
- lib/src/service/users/user_meta.g.dart
- lib/src/service/users/users_service.dart
- pubspec.yaml
> fix: fixed for the issue (#60)

- .vscode/settings.json
- CHANGELOG.md
- example/example.dart
- lib/src/client/client.dart
- lib/src/client/oauth1_client.dart
- lib/src/client/oauth2_client.dart
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- pubspec.yaml
> fix: fixed for the issue (#66)

- test/mocks/client_context_stubs.dart
- test/mocks/mock.dart
- test/mocks/mock.mocks.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/users_service_test.dart
- test/src/twitter_api_test.dart
> test: Added unit tests

- .vscode/settings.json
- codecov.yaml
> feat: fixed for the issue (#73)

- analysis_options.yaml
> refactor: fixed for the issue (#77)

- CHANGELOG.md
- README.md
- lib/src/service/spaces/spaces_service.dart
- pubspec.yaml
- test/src/service/spaces/data/lookup_buyers.json
- test/src/service/spaces/data/lookup_by_creator_ids.json
- test/src/service/spaces/data/lookup_by_id.json
- test/src/service/spaces/data/lookup_by_ids.json
- test/src/service/spaces/data/lookup_tweets.json
- test/src/service/spaces/spaces_service_test.dart
> feat: Added `Spaces Lookup` endpoints (#25)

- lib/src/client/client_context.dart
- lib/src/client/user_context.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- test/mocks/client_context_stubs.dart
- test/src/service/spaces/spaces_service_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/users_service_test.dart
> fix: fixed for the issue (#82)

- README.md
> docs: Added badge

- analysis_options.yaml
- lib/src/client/client.dart
- lib/src/client/client_context.dart
- lib/src/client/oauth1_client.dart
- lib/src/client/oauth2_client.dart
- lib/src/service/base_service.dart
- lib/src/service/compliance/compliance_data.dart
- lib/src/service/compliance/compliance_service.dart
- lib/src/service/lists/lists_service.dart
- lib/src/service/spaces/space_data.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/twitter_service.dart
- lib/src/service/users/users_service.dart
- lib/src/twitter_api.dart
- lib/twitter_api_v2.dart
> refactor: Added linter rules

- .vscode/settings.json
- CHANGELOG.md
- README.md
- lib/src/client/client_context.dart
- lib/src/service/users/users_service.dart
- test/src/service/users/data/create_mute.json
- test/src/service/users/data/destroy_mute.json
- test/src/service/users/data/muting_users.json
- test/src/service/users/users_service_test.dart
> feat: Added `Users Mutes` endpoints (#22)

- .vscode/settings.json
- CHANGELOG.md
- README.md
- lib/src/client/client.dart
- lib/src/client/client_context.dart
- lib/src/client/oauth1_client.dart
- lib/src/client/oauth2_client.dart
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
- test/mocks/client_context_stubs.dart
- test/mocks/mock.mocks.dart
- test/src/service/tweets/data/create_hidden_reply.json
- test/src/service/tweets/data/destroy_hidden_reply.json
- test/src/service/tweets/tweets_service_test.dart
> feat: Added `Tweets Hide Replies` endpoints (#5)

- CHANGELOG.md
- lib/src/client/client.dart
- lib/src/service/base_service.dart
- lib/src/twitter_exception.dart
> fixed: fixed for the issue (#93)

- CHANGELOG.md
- README.md
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
- test/src/service/tweets/data/mentions_of.json
- test/src/service/tweets/data/tweets_of.json
- test/src/service/tweets/tweets_service_test.dart
> feat: Added `Tweets Timelines` endpoints (#11)

- CHANGELOG.md
- README.md
- lib/src/service/users/users_service.dart
- test/src/service/users/data/blocking_users.json
- test/src/service/users/data/create_block.json
- test/src/service/users/data/destroy_block.json
- test/src/service/users/users_service_test.dart
> feat: Added `Users Blocks` endpoints (#20)

- CHANGELOG.md
- README.md
- lib/src/service/lists/lists_service.dart
- test/src/service/lists/data/lookup_tweets.json
- test/src/service/lists/lists_service_test.dart
> feat: Added `Lists Tweet Lookup` endpoint (#26)

- .github/workflows/test.yml
> fix: fixed for the issue (#107)

- STYLEGUIDE.md
> docs: fixed for the issue (#103)

- .github/dependabot.yml
> fix: fixed for the issue (#111)

- .vscode/extensions.json
- .vscode/settings.json
> fix: fixed for the issue (#104)

- CHANGELOG.md
- lib/twitter_api_v2.dart
- pubspec.yaml
- test/src/service/spaces/spaces_service_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/users_service_test.dart
- test/src/twitter_api_test.dart
> fix: fixed for the issue (#122)

- lib/src/service/compliance/compliance_service.dart
- lib/src/service/lists/lists_service.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
> refactor: Applied specifications of `SDK 2.17`

- README.md
> docs: fixed `README.md`

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
> fix: fixed for the issue (#131)

- README.md
> docs: Add lines

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: Added arguments

- README.md
> docs: Added badge for contributors

- CHANGELOG.md
- README.md
- lib/src/auth/oauth_utils.dart
- lib/twitter_api_v2.dart
> feat: Added OAuth utility (#102)

- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
> refactor: refactored #141

- lib/src/service/compliance/compliance_data.dart
- lib/src/service/lists/list_meta.dart
- lib/src/service/media.dart
- lib/src/service/spaces/space_meta.dart
- lib/src/service/tweets/tweet_attachments.dart
- lib/src/service/tweets/tweet_count_data.dart
- lib/src/service/tweets/tweet_count_meta.dart
- lib/src/service/tweets/tweet_data.dart
- lib/src/service/tweets/tweet_geo.dart
- lib/src/service/tweets/tweet_meta.dart
- lib/src/service/users/user_data.dart
- lib/src/service/users/user_meta.dart
- test/mocks/mock.mocks.dart
> fix: ignore `invalid_annotation_target` (#42)

- README.md
> docs: updated `README.md`

- example/example.dart
> refactor: fixed examples

- README.md
> docs: updated examples

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- test/src/service/tweets/tweet_expansion_test.dart
- test/src/service/users/user_expansion_test.dart
> feat: Added `expansions` argument (#142)

- pubspec.yaml
> docs: added `homepage`

- lib/src/service/base_service.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- pubspec.yaml
> refactor: fixed for the issue (#167)

- CHANGELOG.md
- lib/src/service/spaces/space_data.dart
- lib/src/service/spaces/space_data.freezed.dart
- lib/src/service/spaces/space_data.g.dart
- lib/src/service/spaces/space_expansion.dart
- lib/src/service/spaces/spaces_service.dart
- lib/twitter_api_v2.dart
> feat: added `expansions` argument

- CHANGELOG.md
- lib/src/service/lists/list_data.dart
- lib/src/service/lists/list_data.freezed.dart
- lib/src/service/lists/list_data.g.dart
- lib/src/service/lists/list_expansion.dart
- lib/src/service/lists/lists_service.dart
- lib/src/service/media/media_data.dart
- lib/src/service/media/media_data.freezed.dart
- lib/src/service/media/media_data.g.dart
- lib/twitter_api_v2.dart
> feat: added `expansions` argument (#172)

- CHANGELOG.md
- lib/src/service/media/media_data.dart
- lib/src/service/media/media_data.freezed.dart
- lib/src/service/media/media_data.g.dart
- lib/src/service/tweets/tweets_service.dart
- test/src/service/tweets/tweets_service_test.dart
> refactor: fixed types and field

- lib/src/service/tweets/tweet_withheld.dart
> fix: fixed for the issue (#193)

- README.md
> docs: added matrix for endpoints

- README.md
> docs: fixed for the issue (#198)

- CHANGELOG.md
- README.md
- pubspec.yaml
> docs: fixed for the issue (#200)

- README.md
> docs: fixed orders and content

- README.md
> docs: removed badge

- i18n/DISCLAIMER.md
> docs: added i18n folder

- i18n/README-JA.md
> docs: added readme for japanese (#213)

- i18n/README-JA.md
> docs: fixed expression

- i18n/README-JA.md
> docs: fixed markdown

- .all-contributorsrc
> added files

- CHANGELOG.md
- README.md
- i18n/README-JA.md
- i18n/README-VI.md
> refactor: fixed links

- CHANGELOG.md
- README.md
- i18n/README-BN.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-VI.md
> docs: refactored language links

- STYLEGUIDE.md
> docs: fixed for the issue (#105)

- CHANGELOG.md
> docs: added changes

- lib/src/service/media/media_data.freezed.dart
- lib/src/service/media/media_data.g.dart
> refactor: fixed generated file

- CHANGELOG.md
- lib/src/service/compliance/compliance_service.dart
- lib/src/service/lists/lists_service.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- pubspec.yaml
> docs: added dartdocs (#263)

- CHANGELOG.md
- lib/src/service/twitter_response.dart
- test/src/service/twitter_response_test.dart
> feat: added `toJson` to `TwitterResponse` (#274)

- CHANGELOG.md
- lib/src/service/tweets/sort_order.dart
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
- test/src/service/tweets/sort_order_test.dart
> feat: added `sortOrder` parameters (#284)

- README.md
- example/example.dart
> docs: fixed for the issue (#278)

- lib/src/service/tweets/tweets_service.dart
> feat: Support `start_time` and `end_time` parameters

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> fix: fixed for the issue (#288)

- CHANGELOG.md
- lib/src/service/media/media_data.freezed.dart
- lib/src/service/media/variant.dart
- lib/src/service/media/variant.freezed.dart
- lib/src/service/media/variant.g.dart
- lib/src/service/places/place_data.g.dart
> refactor: fixed for the issue (#292)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: added `sinceId` parameter (#285)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: added `excludeReplyUserIds` parameter (#283)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: added `untilTweetId` (#286)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: added `directMessageDeepLink` (#279)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: added `placeId` parameter (#280)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: fixed for the issue (#282)

- CHANGELOG.md
- README.md
- example/example.dart
- i18n/README-BN.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-VI.md
- lib/src/service/tweets/filtering_rule_data.dart
- lib/src/service/tweets/filtering_rule_data.freezed.dart
- lib/src/service/tweets/filtering_rule_data.g.dart
- lib/src/service/tweets/filtering_rule_param.dart
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
- test/src/service/tweets/tweets_service_test.dart
> fix!: fixed for the issue (#312)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
- test/src/service/tweets/tweets_service_test.dart
> feat: fixed for the issue (#311)

- CHANGELOG.md
- lib/src/service/tweets/tweet_count_granularity.dart
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
- test/src/service/tweets/tweet_count_granularity_test.dart
> feat: fixed for the issue (#310)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: fixed for the issue (#309)

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/tweets/tweet_exclude_type.dart
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
- test/src/service/tweets/tweet_exclude_type.dart
> 308 support exclude parameter for lookuptweets

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: fixed for the issue (#307)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
> feat: fixed for the issue (#305)

- CHANGELOG.md
- lib/src/service/tweets/tweet_poll_param.dart
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
- test/src/service/tweets/tweets_service_test.dart
> fix!: fixed for the issue (#322)

- README.md
- i18n/README-BN.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-VI.md
Created `README-ES.md` in the i18n folder. I copied and pasted the English version (README.md) and translated line by line into Spanish (except for Names and code snippets, etc.)
- [N/A] I have updated/added tests for ALL new/updated/fixed functionality.
- [N/A] I have updated/added relevant examples in `examples`.
N/A - just created a Spanish version of the README.md file for translation
Hi @myConsciousness - here is my PR! Please let me know if you need anything else or if there is …
> docs: Translated README doc into Spanish for issue #213

- CHANGELOG.md
- lib/src/service/spaces/spaces_service.dart
- pubspec.yaml
> feat: fixed for the issue (#324)

- .all-contributorsrc
> docs: added `README-ES.md`

- CHANGELOG.md
- lib/src/service/common/includes.dart
- lib/src/service/common/includes.freezed.dart
- lib/src/service/common/includes.g.dart
- lib/src/service/spaces/space_expansion.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/spaces/topic_data.dart
- lib/src/service/spaces/topic_data.freezed.dart
- lib/src/service/spaces/topic_data.g.dart
- lib/src/service/spaces/topic_field.dart
- lib/twitter_api_v2.dart
- test/mocks/client_context_stubs.dart
- test/mocks/mock.mocks.dart
- test/src/service/spaces/space_expansion_test.dart
- test/src/service/spaces/topic_field_test.dart
- test/src/service/twitter_response_test.dart
> feat: fixed for the issue (#185)

- i18n/README-DE.md
Added German translation of the Readme.
> docs: added german translation for readme (#213)

- .all-contributorsrc
> docs: Added `i18n/README-DE.md`

- CHANGELOG.md
- lib/src/service/spaces/space_data.g.dart
- lib/src/service/spaces/space_state.dart
- lib/src/service/spaces/topic_data.freezed.dart
- lib/src/service/spaces/topic_data.g.dart
- test/src/service/spaces/space_state_test.dart
> feat: fixed for the issue (#333)

- CHANGELOG.md
- lib/src/client/client.dart
- lib/src/client/client_context.dart
- lib/src/client/oauth1_client.dart
- lib/src/client/oauth2_client.dart
- test/src/service/spaces/space_expansion_test.dart
- test/src/service/users/users_service_test.dart
> feat: fixed for the issue (#329)

- i18n/README-ES.md
> docs: update co author

- i18n/README-ES.md
> docs: add co author

- test/src/twitter_api_test.dart
> test: add unit tests

- CHANGELOG.md
- lib/src/service/base_service.dart
- pubspec.yaml
- test/src/twitter_api_test.dart
> fix: fixed for the issue (#347)

- CHANGELOG.md
- lib/src/twitter_api.dart
- test/src/twitter_api_test.dart
> feat: fixed for the issue (#352)

- .all-contributorsrc
- README.md
- i18n/README-BN.md
- i18n/README-DE.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-VI.md
> All contributors/add eltociear

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/exception/unauthorized_exception.dart
- lib/src/service/base_service.dart
- lib/twitter_api_v2.dart
- test/src/service/compliance/compliance_service_test.dart
- test/src/service/lists/lists_service_test.dart
- test/src/service/spaces/spaces_service_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/twitter_api_test.dart
> feat: fixed for the issue (#348)

- README.md
- example/example.dart
- lib/src/client/retry_policy.dart
- lib/src/config/retry_config.dart
- test/src/client/retry_policy_test.dart
> fix: fixed for the issue (#360)

- README.md
- example/example.dart
- lib/src/config/retry_config.dart
- test/src/client/retry_policy_test.dart
> refactor: fixed for the issue (#360)

- README.md
- example/example.dart
- i18n/README-BN.md
- i18n/README-DE.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-VI.md
- lib/src/client/client_context.dart
- lib/src/client/retry_context.dart
- lib/src/client/retry_policy.dart
- lib/src/client/stream_request.dart
- lib/src/config/retry_config.dart
- lib/src/service/base_service.dart
- lib/twitter_api_v2.dart
- test/mocks/mock.mocks.dart
- test/src/client/retry_policy_test.dart
> fix: fixed for the issue (#362

- README.md
> docs: added sections

- README.md
- example/example.dart
- lib/src/config/retry_config.dart
- test/src/client/retry_policy_test.dart
> fix: fixed for the issue (#371)

- README.md
> docs: fixed sentences

- README.md
- lib/src/client/retry_policy.dart
- lib/src/client/retry_strategy.dart
- lib/src/config/retry_config.dart
- test/src/client/retry_policy_test.dart
- test/src/config/retry_config_test.dart
> refactor: fixed structure and added unit tests

- CHANGELOG.md
> docs: fixed changelog

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/compliance/compliance_service.dart
- lib/src/service/lists/lists_service.dart
- lib/src/service/response_field.dart
- lib/src/service/spaces/spaces_service.dart
- lib/src/service/tweets/tweets_service.dart
- lib/src/service/users/users_service.dart
- pubspec.yaml
- test/src/service/common_expectations.dart
- test/src/service/response_field_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/data/rate_limit_exceeded_error.json
- test/src/service/users/users_service_test.dart
> feat: fixed for the issue (#381)

- pubspec.yaml
> docs: added `issue_tracker`

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
- test/src/service/tweets/tweets_service_test.dart
> fix: fixed for the issue (#382)

- README.md
> doc: fixed for the issue (#388)

- CHANGELOG.md
- pubspec.yaml
> fix: fixed for the issue (#396)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
> fixed: fixed for the issue (#403)

- i18n/README-BN.md
- i18n/README-DE.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-PT.md
- i18n/README-VI.md
Created README-PT.md in the i18n folder. I copied and pasted the English version (README.md) and translated line by line into Portuguese (except for Names and code snippets, etc.)
[N/A] I have updated/added tests for ALL new/updated/fixed functionality.
[N/A] I have updated/added relevant examples in examples.
N/A - just created a Portuguese version of the README.md file for translation
Hi @myConsciousness - here's my PR! I would be extremely happy to help with anything else! 😄😁
> docs: Translated README doc into Portuguese for issue twitter-dart#213

- .all-contributorsrc
> Add `i18n/README-PT.md`

- README.md
> Added link to `/i18n/README-PT.md`

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/config/retry_config.dart
- pubspec.yaml
- test/src/client/retry_policy_test.dart
- test/src/config/retry_config_test.dart
> refactor: fixed for the issue (#409)

- CHANGELOG.md
- lib/src/service/base_service.dart
- lib/src/service/base_upload_service.dart
- lib/src/service/media/media_service.dart
- lib/src/service/media/uploaded_media_data.dart
- lib/src/service/media/uploaded_media_data.freezed.dart
- lib/src/service/media/uploaded_media_data.g.dart
- lib/src/service/twitter_service.dart
- lib/src/twitter_api.dart
- pubspec.yaml
- test/mocks/mock.mocks.dart
> feat: supported the image upload

- CHANGELOG.md
- lib/src/service/media/media_service.dart
- pubspec.yaml
> refactor: fixed for the issue (#427)

- README.md
> docs: added descriptions for media service

- CHANGELOG.md
- lib/src/service/base_media_service.dart
- lib/src/service/media/media_service.dart
- pubspec.yaml
> refactor: refactored the structure

- CHANGELOG.md
- lib/src/service/common/rate_limit.dart
- lib/src/service/common/rate_limit.freezed.dart
- lib/src/service/twitter_stream_response.dart
- pubspec.yaml
- test/mocks/client_context_stubs.dart
- test/mocks/mock.mocks.dart
- test/src/service/common/rate_limit_test.dart
- test/src/service/common_expectations.dart
- test/src/service/filtered_stream_response_test.dart
- test/src/service/media/data/upload_image.json
- test/src/service/media/media_service_test.dart
> feat: fixed for the issue (#444)

- CHANGELOG.md
- lib/src/service/media/media_service.dart
- pubspec.yaml
> fix: fixed for the issue (#447)

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/service/media/media_service.dart
- lib/src/service/media/upload_event.dart
- lib/src/service/media/upload_state.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
> feat: fixed for the issue (#454)

- lib/src/service/base_media_service.dart
- lib/src/service/base_service.dart
- lib/src/service/media/media_service.dart
> refactor: fixed for the issue (#457)

- lib/src/service/media/media_service.dart
- lib/src/service/media/upload_event.dart
- lib/src/service/media/upload_state.dart
- lib/twitter_api_v2.dart
- test/src/service/media/upload_state_test.dart
> refactor: refactored the upload state

- lib/src/service/media/media_service.dart
> doc: fixed documentation

- lib/src/service/media/media_service.dart
> refactor: fixed exception error messages

- README.md
> doc: add document for upload media

- CHANGELOG.md
- lib/src/service/media/media_service.dart
- lib/src/service/media/upload_event.dart
- lib/src/service/media/upload_state.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
- test/src/service/media/upload_event_test.dart
- test/src/service/media/upload_state_test.dart
> fix: fixed for the issue (#466)

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/service/media/media_service.dart
- lib/src/service/media/upload_error.dart
- lib/src/service/media/upload_error.freezed.dart
- lib/src/service/media/upload_error.g.dart
- lib/twitter_api_v2.dart
> feat: fixed for the issue (#456)

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/service/base_service.dart
- lib/src/service/media/media_service.dart
- pubspec.yaml
- test/src/service/media/media_service_test.dart
> feat: fixed for the issue (#435)

- CHANGELOG.md
- lib/src/service/compliance/batch_compliance_data.dart
- lib/src/service/compliance/batch_compliance_data.freezed.dart
- lib/src/service/compliance/batch_compliance_data.g.dart
- lib/src/service/compliance/compliance_service.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
- test/src/service/compliance/compliance_service_test.dart
> fix: fixed for the issue (#462)

- CHANGELOG.md
- lib/src/service/tweets/tweet_data.dart
- lib/src/service/tweets/tweet_data.freezed.dart
- lib/src/service/tweets/tweet_data.g.dart
- test/src/service/filtered_stream_response_test.dart
- test/src/service/twitter_response_test.dart
> feat: fixed for the issue (#471)

- CHANGELOG.md
- README.md
- example/example.dart
- i18n/README-BN.md
- i18n/README-DE.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-PT.md
- i18n/README-VI.md
- lib/src/twitter_api.dart
- pubspec.yaml
- test/src/twitter_api_test.dart
> fix: fixed for the issue (#483)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service_extension.dart
- pubspec.yaml
- test/src/service/tweets/tweets_service_extension_test.dart
> fix: fixed for the issue (#495)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service_extension.dart
- pubspec.yaml
- test/src/service/tweets/tweets_service_extension_test.dart
> fix: renamed method

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/service/media/media_service.dart
- lib/src/service/media/uploaded_media_data.dart
- lib/src/service/media/uploaded_media_data.freezed.dart
- lib/src/service/media/uploaded_media_data.g.dart
- pubspec.yaml
- test/src/service/media/media_service_test.dart
> refactor: deprecated `UploadedMediaData.mediaId`

- README.md
> docs: refactored contents

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/service/tweets/filtering/filtering_rule.dart
- pubspec.yaml
- test/src/service/tweets/filtering/filtering_rule_test.dart
> fix: fixed for the issue (#515)

- .vscode/settings.json
- CHANGELOG.md
- lib/src/service/media/media_category.dart
- lib/src/service/media/media_service.dart
- pubspec.yaml
- test/src/service/media/media_category_test.dart
> feat: fixed for the issue (#508)

- README.md
> docs: update contents

- CHANGELOG.md
- lib/src/service/media/media_service.dart
> feat: fixed for the issue (#436)

- CHANGELOG.md
- lib/src/service/media/media_service.dart
- pubspec.yaml
> fix: fixed for the issue (#510)

- CHANGELOG.md
- pubspec.yaml
- test/src/service/common_expectations.dart
> fix: fixed for the issue (#528)

- lib/src/service/dms/direct_messages_service.dart
- lib/src/service/twitter_service.dart
- lib/src/twitter_api.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
> feat: added `DirectMessagesService`

- CHANGELOG.md
- lib/src/service/media/uploaded_media_data.dart
- lib/src/service/media/uploaded_media_data.freezed.dart
- lib/src/service/media/uploaded_media_data.g.dart
- lib/src/service/tweets/filtering/filtering_rule.dart
> fix: removed deprecated features

- README.md
- example/example.dart
- pubspec.yaml
> fix: fixed for the issue (#531)

- pubspec.yaml
> fix: fixed for the issue (#542)

- CHANGELOG.md
- lib/src/service/dms/message_attachments_param.dart
- lib/src/service/dms/message_param.dart
- lib/src/service/media/media_category.dart
- lib/src/service/media/media_mime_type.dart
- lib/src/service/media/media_service.dart
- lib/twitter_api_v2.dart
- test/mocks/mock.mocks.dart
- test/src/service/media/media_category_test.dart
- test/src/service/media/media_mime_type_test.dart
> feat: fixed for the issue (#547)

- CHANGELOG.md
- pubspec.yaml
> fix: fixed for the issue (#560)

- CHANGELOG.md
- lib/src/service/base_service.dart
- pubspec.yaml
- test/mocks/client_context_stubs.dart
- test/src/service/common_expectations.dart
- test/src/service/dms/direct_messages_service_test.dart
- test/src/service/lists/lists_service_test.dart
- test/src/service/spaces/spaces_service_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/users_service_test.dart
> fix: fixed for the issue (#562)

- CHANGELOG.md
- lib/src/service/tweets/filtering/operation/standalone_operation.dart
- lib/src/service/tweets/filtering/operator/standalone/entity.dart
- lib/src/service/tweets/filtering/syntax/standalone_syntax.dart
- test/src/service/tweets/filtering/filtering_rule_test.dart
- test/src/service/tweets/filtering/operator/standalone/entity_test.dart
> feat: fixed for the issue (#557)

- CHANGELOG.md
- lib/src/service/tweets/filtering/operation/standalone_operation.dart
- lib/src/service/tweets/filtering/operator/standalone/context.dart
- lib/src/service/tweets/filtering/syntax/standalone_syntax.dart
- test/src/service/tweets/filtering/filtering_rule_test.dart
- test/src/service/tweets/filtering/operation/standalone_operation_test.dart
- test/src/service/tweets/filtering/operator/standalone/context_test.dart
> feat: fixed for the issue (#556)

- CHANGELOG.md
- README.md
- docs/getting-started-with-filtering-rule-object.md
> docs: fixed for the issue (#558)

- CHANGELOG.md
- lib/src/service/tweets/tweet_edit_controls.dart
- lib/src/service/tweets/tweet_edit_controls.freezed.dart
- lib/src/service/tweets/tweet_edit_controls.g.dart
- test/src/service/tweets/data/lookup_by_id.json
- test/src/service/tweets/tweets_service_test.dart
> fix: fixed for the issue (#571)

- CHANGELOG.md
- README.md
- doc/getting-started-with-filtering-rule-object.md
- lib/src/service/base_service.dart
- lib/src/service/common/locale.g.dart
- lib/src/service/tweets/tweet_data.g.dart
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
> fix: fixed for the issue (#570)

- .vscode/settings.json
- CHANGELOG.md
- README.md
- lib/src/service/geo/geo_service.dart
- test/src/service/geo/data/lookup_reversed_geocoded_locations.json
- test/src/service/geo/geo_service_test.dart
> fix: Prepare v4.6.0

- CHANGELOG.md
- lib/src/service/base_service.dart
- pubspec.yaml
- test/src/service/tweets/tweets_service_test.dart
> fix: fixed for the issue (#592)

- CHANGELOG.md
- README.md
- lib/src/core/client/client_context.dart
- lib/src/core/client/client_resolver.dart
- lib/src/core/client/oauth2_client.dart
- lib/src/core/client/user_context.dart
- lib/src/service/compliance/compliance_service.dart
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
- test/mocks/client_context_stubs.dart
- test/src/core/client/client_resolver_test.dart
- test/src/core/client/user_context_test.dart
- test/src/service/common_expectations.dart
- test/src/service/compliance/compliance_service_test.dart
- test/src/service/dms/direct_messages_service_test.dart
- test/src/service/lists/lists_service_test.dart
- test/src/service/spaces/spaces_service_test.dart
- test/src/service/tweets/tweets_service_test.dart
- test/src/service/users/users_service_test.dart
> fix: fixed for the issue (#596)

- CHANGELOG.md
- README.md
- lib/src/core/oauth_response.dart
- lib/src/core/oauth_response.freezed.dart
- lib/src/core/oauth_response.g.dart
- lib/src/core/scope.dart
- lib/src/core/util/oauth_utils.dart
- lib/twitter_api_v2.dart
- test/src/core/auth/oauth_utils_test.dart
- test/src/core/client/scope_test.dart
- test/src/core/client/user_context_test.dart
> feat: fixed for the issue (#604)

- CHANGELOG.md
- pubspec.yaml
> docs: prepare v4.7.1

- CHANGELOG.md
- lib/src/service/users/users_service.dart
- test/src/service/users/data/create_report.json
- test/src/service/users/users_service_test.dart
> feat: fixed for the issue (#618)

- lib/src/service/tweets/tweets_service.dart
> added use of tokens other than AppOnly in tweets_service

- lib/src/service/tweets/tweets_service.dart
- test/src/service/tweets/tweets_service_test.dart
> fix: fixed for the issue (#619)

- README.md
> docs: add links

- lib/src/core/client/stream_response.dart
- lib/src/core/http_method.dart
- lib/src/core/https_status.dart
- lib/src/core/service_helper.dart
- lib/src/service/base_media_service.dart
- lib/src/service/base_service.dart
- lib/src/service/compliance/job_status.dart
- lib/src/service/compliance/job_type.dart
- lib/src/service/geo/geo_service.dart
- lib/src/service/geo/place_type.dart
- lib/src/service/response/filtered_stream_response.dart
- lib/src/service/response/pagination_response.dart
- lib/src/service/response/twitter_request.dart
- lib/src/service/response/twitter_response.dart
- lib/src/service/spaces/space_state.dart
- lib/src/service/trends/trends_service.dart
- lib/src/service/tweets/exclude_tweet_type.dart
- lib/src/service/tweets/reply_setting.dart
- lib/src/service/tweets/sort_order.dart
- lib/src/service/tweets/tweet_count_granularity.dart
- lib/src/service/tweets/tweets_service.dart
- lib/twitter_api_v2.dart
- test/mocks/client_context_stubs.dart
- test/src/core/http_method_test.dart
- test/src/core/http_status_test.dart
- test/src/service/compliance/job_status_test.dart
- test/src/service/compliance/job_type_test.dart
- test/src/service/response/filtered_stream_response_test.dart
- test/src/service/response/twitter_response_test.dart
> feat: fixed for the issue (#637)

- CHANGELOG.md
- lib/src/service/tweets/decahose_partition.dart
- test/src/service/tweets/decahose_partition_test.dart
> refactor: fixed for the issue (#639)

- CHANGELOG.md
- lib/twitter_api_v2.dart
- pubspec.yaml
> fix: fixed for the issue (#641)

- CHANGELOG.md
- example/example.dart
- lib/src/service/users/user_data.dart
- lib/src/service/users/user_data.freezed.dart
- lib/src/service/users/user_data.g.dart
- lib/src/service/users/user_field.dart
- lib/src/service/users/user_verified_type.dart
- lib/twitter_api_v2.dart
- pubspec.yaml
- test/src/service/users/user_field_test.dart
- test/src/service/users/user_verified_type_test.dart
> feat: fixed for the issue (#646)

- CHANGELOG.md
- lib/src/core/https_status.dart
- pubspec.yaml
- test/src/core/http_status_test.dart
> fix: fixed for the issue (#651)

- CHANGELOG.md
- lib/src/service/tweets/tweets_service.dart
- pubspec.yaml
> fix: fixed for the issue (#647)

- CHANGELOG.md
- lib/src/service/lists/lists_service.dart
- pubspec.yaml
> fix: fixed for the issue (#657)

- README.md
- i18n/README-BN.md
- i18n/README-CN.md
- i18n/README-DE.md
- i18n/README-ES.md
- i18n/README-FR.md
- i18n/README-JA.md
- i18n/README-PT.md
- i18n/README-VI.md
> docs: Added readme-cn
